In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/weather.csv")
df

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0     11/1/2007  Canberra      8.0     24.3       0.0          3.4       6.3   
1     11/2/2007  Canberra     14.0     26.9       3.6          4.4       9.7   
2     11/3/2007  Canberra     13.7     23.4       3.6          5.8       3.3   
3     11/4/2007  Canberra     13.3     15.5      39.8          7.2       9.1   
4     11/5/2007  Canberra      7.6     16.1       2.8          5.6      10.6   
..          ...       ...      ...      ...       ...          ...       ...   
361  10/27/2008  Canberra      9.0     30.7       0.0          7.6      12.1   
362  10/28/2008  Canberra      7.1     28.4       0.0         11.6      12.7   
363  10/29/2008  Canberra     12.5     19.9       0.0          8.4       5.3   
364  10/30/2008  Canberra     12.5     26.9       0.0          5.0       7.1   
365  10/31/2008  Canberra     12.3     30.2       0.0          6.0      12.6   

    WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0            NW           30.0         SW  ...          29       1019.7   
1           ENE           39.0          E  ...          36       1012.4   
2            NW           85.0          N  ...          69       1009.5   
3            NW           54.0        WNW  ...          56       1005.5   
4           SSE           50.0        SSE  ...          49       1018.3   
..          ...            ...        ...  ...         ...          ...   
361         NNW           76.0        SSE  ...          15       1016.1   
362           N           48.0        NNW  ...          22       1020.0   
363         ESE           43.0        ENE  ...          47       1024.0   
364          NW           46.0        SSW  ...          39       1021.0   
365          NW           78.0         NW  ...          13       1009.6   

     Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0         1015.0         7         7     14.4     23.6         No      3.6   
1         1008.4         5         3     17.5     25.7        Yes      3.6   
2         1007.2         8         7     15.4     20.2        Yes     39.8   
3         1007.0         2         7     13.5     14.1        Yes      2.8   
4         1018.5         7         7     11.1     15.4        Yes      0.0   
..           ...       ...       ...      ...      ...        ...      ...   
361       1010.8         1         3     20.4     30.0         No      0.0   
362       1016.9         0         1     17.2     28.2         No      0.0   
363       1022.8         3         2     14.5     18.3         No      0.0   
364       1016.2         6         7     15.8     25.9         No      0.0   
365       1009.2         1         1     23.8     28.6         No      0.0   

     RainTomorrow  
0             Yes  
1             Yes  
2             Yes  
3             Yes  
4              No  
..            ...  
361            No  
362            No  
363            No  
364            No  
365            No  

[366 rows x 24 columns]

In [ ]:
df['RainTomorrow'].value_counts()

RainTomorrow
No     300
Yes     66
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

Date              0
Location          0
MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          3
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64

In [ ]:
df = df.dropna()
df.isnull().sum()

Date             0
Location         0
MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [ ]:
df['RainTomorrow'].value_counts()

RainTomorrow
No     268
Yes     60
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
for column in df.columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

/tmp/ipython-input-2837268328.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = label_encoders[column].fit_transform(df[column])
/tmp/ipython-input-2837268328.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = label_encoders[column].fit_transform(df[column])
/tmp/ipython-input-2837268328.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: h

In [ ]:
df

Date  Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0      59         0       90      111         0           15        43   
1      70         0      138      130        16           20        75   
2      81         0      135      106        16           27        24   
3      83         0      133       42        43           34        69   
4      84         0       86       46        13           26        84   
..    ...       ...      ...      ...       ...          ...       ...   
361    47         0      100      152         0           36        99   
362    48         0       81      141         0           51       104   
363    49         0      125       78         0           40        36   
364    51         0      125      130         0           23        50   
365    52         0      123      150         0           28       103   

     WindGustDir  WindGustSpeed  WindDir9am  ...  Humidity3pm  Pressure9am  \
0              7              8          12  ...           15           93   
1              1             12           0  ...           22           37   
2              7             33           3  ...           55           20   
3              7             20          14  ...           42            7   
4             10             18          10  ...           35           84   
..           ...            ...         ...  ...          ...          ...   
361            6             29          10  ...            2           64   
362            3             17           6  ...            8           95   
363            2             14           1  ...           33          131   
364            7             16          11  ...           25          103   
365            7             30           7  ...            0           21   

     Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0             82         7         7       95      129          0       16   
1             27         5         3      123      145          1       16   
2             22         8         7      103       99          1       43   
3             21         2         7       88       50          1       13   
4            113         7         7       68       60          1        0   
..           ...       ...       ...      ...      ...        ...      ...   
361           46         1         3      148      167          0        0   
362           98         0         1      120      160          0        0   
363          147         3         2       96       81          0        0   
364           91         6         7      107      146          0        0   
365           34         1         1      165      163          0        0   

     RainTomorrow  
0               1  
1               1  
2               1  
3               1  
4               0  
..            ...  
361             0  
362             0  
363             0  
364             0  
365             0  

[328 rows x 24 columns]

In [ ]:
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [ ]:
X = df.drop(columns=['Date', 'RainTomorrow'])
y = df['RainTomorrow']

In [ ]:
X

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustDir  \
0           0       90      111         0           15        43            7   
1           0      138      130        16           20        75            1   
2           0      135      106        16           27        24            7   
3           0      133       42        43           34        69            7   
4           0       86       46        13           26        84           10   
..        ...      ...      ...       ...          ...       ...          ...   
361         0      100      152         0           36        99            6   
362         0       81      141         0           51       104            3   
363         0      125       78         0           40        36            2   
364         0      125      130         0           23        50            7   
365         0      123      150         0           28       103            7   

     WindGustSpeed  WindDir9am  WindDir3pm  ...  Humidity9am  Humidity3pm  \
0                8          12           7  ...           29           15   
1               12           0          13  ...           41           22   
2               33           3           5  ...           43           55   
3               20          14          13  ...           23           42   
4               18          10           2  ...           29           35   
..             ...         ...         ...  ...          ...          ...   
361             29          10           7  ...            1            2   
362             17           6           6  ...            6            8   
363             14           1           1  ...           24           33   
364             16          11          14  ...           30           25   
365             30           7          14  ...            4            0   

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0             93           82         7         7       95      129   
1             37           27         5         3      123      145   
2             20           22         8         7      103       99   
3              7           21         2         7       88       50   
4             84          113         7         7       68       60   
..           ...          ...       ...       ...      ...      ...   
361           64           46         1         3      148      167   
362           95           98         0         1      120      160   
363          131          147         3         2       96       81   
364          103           91         6         7      107      146   
365           21           34         1         1      165      163   

     RainToday  RISK_MM  
0            0       16  
1            1       16  
2            1       43  
3            1       13  
4            1        0  
..         ...      ...  
361          0        0  
362          0        0  
363          0        0  
364          0        0  
365          0        0  

[328 rows x 22 columns]

In [ ]:
y

0      1
1      1
2      1
3      1
4      0
      ..
361    0
362    0
363    0
364    0
365    0
Name: RainTomorrow, Length: 328, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42

)

In [ ]:
from sklearn.preprocessing import StandardScaler

#s = StandardScaler()
#X_train = s.fit_transform(X_train)
#X_test = s.transform(X_test)

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((262, 22), (66, 22), (262,), (66,))

In [ ]:
dt = DecisionTreeClassifier(random_state=42)
rf = RandomForestClassifier(n_estimators=200, random_state=42)
lr = LogisticRegression(max_iter=500)
knn = KNeighborsClassifier(n_neighbors=50)

In [ ]:
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)
lr.fit(X_train, y_train)
knn.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


KNeighborsClassifier(n_neighbors=50)

In [ ]:
dt_y_pred = dt.predict(X_test)
rf_y_pred = rf.predict(X_test)
lr_y_pred = lr.predict(X_test)
knn_y_pred = knn.predict(X_test)

In [ ]:
y_test

365    0
28     0
36     1
301    0
305    0
      ..
356    0
72     1
320    0
81     0
146    0
Name: RainTomorrow, Length: 66, dtype: int64

In [ ]:
dt_y_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0])

In [ ]:
rf_y_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0])

In [ ]:
lr_y_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0])

In [ ]:
knn_y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

dt_acc = accuracy_score(y_test, dt_y_pred)
rf_acc = accuracy_score(y_test, rf_y_pred)
lr_acc = accuracy_score(y_test, lr_y_pred)
knn_acc = accuracy_score(y_test, knn_y_pred)


print("=== DT Test Accuracy ===")
print(f"Decision Tree : {dt_acc:.4f}")
print (confusion_matrix(y_test,dt_y_pred))

print("=== RF Test Accuracy ===")
print(f"Random Forest : {rf_acc:.4f}")
print (confusion_matrix(y_test,rf_y_pred))

print("=== LR Test Accuracy ===")
print(f"Logistic Reg. : {lr_acc:.4f}")
print (confusion_matrix(y_test,lr_y_pred))

print("=== KNN Test Accuracy ===")
print(f"KNeighbors : {knn_acc:.4f}")
print (confusion_matrix(y_test,knn_y_pred))

=== DT Test Accuracy ===
Decision Tree : 1.0000
[[54  0]
 [ 0 12]]
=== RF Test Accuracy ===
Random Forest : 1.0000
[[54  0]
 [ 0 12]]
=== LR Test Accuracy ===
Logistic Reg. : 1.0000
[[54  0]
 [ 0 12]]
=== KNN Test Accuracy ===
KNeighbors : 0.8182
[[53  1]
 [11  1]]


In [ ]:
import numpy as np
from sklearn import metrics

k = 10
acc_array = np.zeros(k)
for k in np.arange(1, k+1, 1):
    model = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    acc_array[k-1] = acc

max_acc = np.amax(acc_array)
acc_list = list(acc_array)
k = acc_list.index(max_acc)
print("정확도", max_acc, "으로 최적의 k는", k+1, "입니다.")

정확도 0.8333333333333334 으로 최적의 k는 3 입니다.


In [70]:
knn = KNeighborsClassifier(n_neighbors=3)

In [71]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [72]:
knn_y_pred2 = knn.predict(X_test)
knn_y_pred2

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [73]:
knn_acc2 = accuracy_score(y_test, knn_y_pred2)

print("=== KNN Test Accuracy ===")
print(f"KNeighbors : {knn_acc:.4f}")
print (confusion_matrix(y_test,knn_y_pred))

print("=== KNN Test Accuracy ===")
print(f"KNeighbors : {knn_acc2:.4f}")
print (confusion_matrix(y_test,knn_y_pred2))

=== KNN Test Accuracy ===
KNeighbors : 0.8182
[[53  1]
 [11  1]]
=== KNN Test Accuracy ===
KNeighbors : 0.8333
[[50  4]
 [ 7  5]]
